apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    id: very-important 
  name: deploy-important
  namespace: project-tiger 
spec:
  replicas: 3 
  selector:
    matchLabels:
      id: very-important 
  template:
    metadata:
      labels:
        id: very-important 
    spec:
      containers:
      - image: nginx:1.17.6-alpine
        name: container1
      - image: curlimages/curl 
        name: container2 
        command:
        - sleep
        - "4800"
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector: 
              matchExpressions: 
              - key: id 
                operator: In 
                values: 
                - very-important 
            topologyKey: kubernetes.io/hostname 
